// src/app/layout.js
import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900 font-[Cinzel] min-h-screen">
        {children}
      </body>
    </html>
  );
}
